/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppZohoRouteImport } from './routes/_app/zoho'
import { Route as AppPowerbiRouteImport } from './routes/_app/powerbi'
import { Route as AppDataRouteImport } from './routes/_app/data'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppZohoRoute = AppZohoRouteImport.update({
  id: '/zoho',
  path: '/zoho',
  getParentRoute: () => AppRoute,
} as any)
const AppPowerbiRoute = AppPowerbiRouteImport.update({
  id: '/powerbi',
  path: '/powerbi',
  getParentRoute: () => AppRoute,
} as any)
const AppDataRoute = AppDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/data': typeof AppDataRoute
  '/powerbi': typeof AppPowerbiRoute
  '/zoho': typeof AppZohoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/data': typeof AppDataRoute
  '/powerbi': typeof AppPowerbiRoute
  '/zoho': typeof AppZohoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/data': typeof AppDataRoute
  '/_app/powerbi': typeof AppPowerbiRoute
  '/_app/zoho': typeof AppZohoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/data' | '/powerbi' | '/zoho'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/data' | '/powerbi' | '/zoho'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/data'
    | '/_app/powerbi'
    | '/_app/zoho'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/zoho': {
      id: '/_app/zoho'
      path: '/zoho'
      fullPath: '/zoho'
      preLoaderRoute: typeof AppZohoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/powerbi': {
      id: '/_app/powerbi'
      path: '/powerbi'
      fullPath: '/powerbi'
      preLoaderRoute: typeof AppPowerbiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/data': {
      id: '/_app/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AppDataRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDataRoute: typeof AppDataRoute
  AppPowerbiRoute: typeof AppPowerbiRoute
  AppZohoRoute: typeof AppZohoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDataRoute: AppDataRoute,
  AppPowerbiRoute: AppPowerbiRoute,
  AppZohoRoute: AppZohoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
